export const NotificationTypes = {
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_ACCEPT: 'FRIEND_ACCEPT', // UI also supports FRIEND_ACCEPTED
  MATCH_INVITE: 'MATCH_INVITE',
  MATCH_UPDATED: 'MATCH_UPDATED',
  MATCH_REMINDER: 'MATCH_REMINDER',
  MATCH_CONFIRMED: 'MATCH_CONFIRMED',
  MATCH_DECLINED: 'MATCH_DECLINED',
};

export default NotificationTypes;
